### ISSUE TITLE
process.env.DATABASE_URL = UNDEFINED

### ISSUE THREAD

**Issue by amineElabbadi** [aneagoie/smart-brain-api#13]
HI, Iiam using Heroku and for some reason, when I use process.env.DATABASE_URL to connect I get a connection error. When I set all the credentials manually (URL, username, password, db, port) the connection works. also when i do git push heroku master
can't register.

const db = knex ({
  client: 'pg',
  password : 'test',
  connection: {
    host: process.env.DATABASE_URL,
    ssl: true,
  }
});
reply
app is running on port undefined

**Comment by Monika39-maker** [comment]
Thanks for mentioning this. I am having the same problem. Dont know what to do

**Comment by sravya270897** [comment]
Thanks for raising this. I am facing the same issue.

**Comment by hseoy** [comment]
Hello, I solved it as below.

```
const db = knex({
    client: 'pg',
    connection: {
        connectionString: process.env.DATABASE_URL,
        ssl: { rejectUnauthorized: false },
    }
});
```

**Comment by S-Raza-N** [comment]
connection: {
    connectionString:"postgres://jqesonsaescvxi:05f1fb9cb204c4faf2cca445......." ,
     ssl: { rejectUnauthorized: false },
  }
try changing the host to a connectionString as process.env.DATABASE_URL is basically a envoirnment variable configured by heroku and return the url of the database.

**Comment by Mirobelak** [comment]
> 

Yes, it worked for me ! Thank. Change connectionString to your DATABASE_URL..

**Comment by uranuslucky** [comment]
if process.env.DATABASE_URL is replaced by static string, then it might be unsecure.
isn't there any other way to fix that issue to resolve process.env.DATABASE_URL is undefined ?

**Comment by mammad-linuxer** [comment]
> if process.env.DATABASE_URL is replaced by static string, then it might be unsecure. isn't there any other way to fix that issue to resolve process.env.DATABASE_URL is undefined ?

I Used the command: `npx tsx --env-file=.env ./db/seed.ts` so that the file has access to .env vars while being exequted. 

Here's the File Content:

//////////============================\\\\\\\\\\\\\\\\\
// import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import sampleData from "./sample-data";

async function main() {
  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
  await console.log(adapter.provider);
  const prisma = new PrismaClient({ adapter });
  await prisma.product.deleteMany();
  await prisma.product.createMany({ data: sampleData.products });

  console.log("Database Seeded Successfully");
}

main();

// FOR EXECUTING THIS FILE, JUST USE THE COMMAND:
// npx tsx --env-file=.env ./db/seed.ts
`
//////////============================\\\\\\\\\\\\\\\\\


You can also use the `import "dotenv/config"` in the first line of the code. BUT idk how insecure this approach is.
